// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Post-Comment-Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Post-Comment-Test', async function() {
    await driver.get("https://sage-83fmdi6qa-lorisvenyor.vercel.app/")
    await driver.manage().window().setRect({ width: 1082, height: 692 })
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .MuiButtonBase-root:nth-child(3) .MuiTypography-root")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(4) .MuiButton-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiSvgIcon-fontSizeInherit > path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiSvgIcon-fontSizeInherit > path")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(3) .MuiCardActions-root")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(3) .MuiCardActions-root")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(3) > .MuiPaper-root .MuiButton-root")).click()
    await driver.findElement(By.css(".MuiButton-text")).click()
    {
      const element = await driver.findElement(By.css(".MuiTypography-root > .MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("fullWidth")).click()
    await driver.findElement(By.id("fullWidth")).sendKeys("hiiiiiiiiiiii")
    await driver.findElement(By.css(".MuiButton-sizeMedium")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-sizeMedium"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
