# this pipeline is temporary
# add scripts on unit testing + backend testing

stages:
    - build
    - lint
    - integration

lint:
    stage: lint
    before_script:
        - echo "installing modules and dependencies..."
        - cd src/sage-project
        - npm ci
    script:
        - echo "running lint tests"
        - npm run lint

build:
    stage: build
    script:
      - echo "building...."
      - cd src/sage-project
      - npm run build

integration:
    stage: integration
    script:
      - echo "running tests"
      - cd src/sage-project
      - npm run test
