// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Invite-Member-Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Invite-Member-Test', async function() {
    await driver.get("https://sage-83fmdi6qa-lorisvenyor.vercel.app/")
    await driver.manage().window().setRect({ width: 1082, height: 692 })
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .MuiButtonBase-root:nth-child(3) .MuiTypography-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .MuiButtonBase-root:nth-child(3) .MuiTypography-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiGrid-root:nth-child(2) > .MuiPaper-root .MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiGrid-root:nth-child(2) > .MuiPaper-root .MuiButton-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiContainer-root > .MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiContainer-root > .MuiButton-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css("div:nth-child(2) > .MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("div:nth-child(2) > .MuiButton-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("group-name")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-root:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("group-name")).sendKeys("chloe.ward35@mail.dcu.ie")
    await driver.findElement(By.css(".MuiButton-root:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".css-bte7tm > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-bte7tm > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .jss27 .MuiTypography-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .jss27 .MuiTypography-root")).click()
  })
})
