// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Make-Group-Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Make-Group-Test', async function() {
    await driver.get("https://sage-83fmdi6qa-lorisvenyor.vercel.app/")
    await driver.manage().window().setRect({ width: 1082, height: 692 })
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .MuiButtonBase-root:nth-child(3) .MuiTypography-root")).click()
  })
})
