

export const Sports = ["airsoft",
                "amateursportsteams",
                "archery",
                "badminton",
                "baseballfields",
                "basketballcourts",
                "beachvolleyball",
                "fencing",
                "football",
                "golf",
                "gymnastics",
                "handball",
                "horsebackriding",
                "horseracing",
                "mountainbiking",
                "paddleboarding",
                "races",
                "racingexperience",
                "rafting",
                "sport_equipment_hire",
                "sports_clubs",
                "squash",
                "tennis",
                "volleyball"]
