// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create-Event-Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create-Event-Test', async function() {
    await driver.get("https://sage-83fmdi6qa-lorisvenyor.vercel.app/")
    await driver.manage().window().setRect({ width: 1295, height: 695 })
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .MuiButtonBase-root:nth-child(3) .MuiTypography-root")).click()
    await driver.findElement(By.css(".MuiButton-text")).click()
    await driver.findElement(By.css("div:nth-child(4) > .MuiButton-root")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(2) .MuiCardMedia-root")).click()
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.css(".jss88:nth-child(1) .MuiButton-root")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(9) > .MuiButtonBase-root")).click()
    await driver.findElement(By.css(".MuiButton-root:nth-child(2)")).click()
    await driver.findElement(By.css(".component_swipingWrapper__Ufkmb:nth-child(5) > .ant-btn")).click()
    await driver.findElement(By.css("div:nth-child(31) .ant-btn-primary > span")).click()
    await driver.findElement(By.css(".anticon-close > svg")).click()
    await driver.findElement(By.css(".anticon-check")).click()
    await driver.findElement(By.css(".anticon-close path")).click()
    await driver.findElement(By.css(".anticon-check path")).click()
    await driver.findElement(By.css(".anticon-close > svg")).click()
  })
})
