// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login-SignUp-ForgetPassword-LandingPage-test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login-SignUp-ForgetPassword-LandingPage-test', async function() {
    await driver.get("https://sage-83fmdi6qa-lorisvenyor.vercel.app/")
    await driver.manage().window().setRect({ width: 550, height: 691 })
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.css(".MuiPaper-root")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.css(".MuiPaper-root")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.linkText("Forgot your password?")).click()
    await driver.findElement(By.linkText("Log in")).click()
    await driver.findElement(By.linkText("Sign up")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.linkText("Log in")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("email")).click()
  })
})
