// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login-Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login-Test', async function() {
    await driver.get("https://sage-83fmdi6qa-lorisvenyor.vercel.app/")
    await driver.manage().window().setRect({ width: 1295, height: 695 })
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("chloe.ward35@mail.dcu.ie")
    await driver.findElement(By.id("password")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("password")).sendKeys("1234567890")
    await driver.findElement(By.css(".MuiButton-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
